filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ./haproxy/log/haproxy-*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]
  username: "elastic"
  password: "changeme"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~